name: Branchyng Strategy
on:
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - dev/*

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: createBranch
    steps:
      - uses: actions/checkout@v3
      - name: Make changes to pull request
        if: github.event.pull_request.merged
        run:
          curl -X POST -u $GITHUB_TOKEN:x-oauth-basic -H "Accept:application/vnd.github+json" https://api.github.com/repos/bgarrido2314/branching-strategy/pulls -d '{"title":"Dev-Qa","body":"Please pull these new changes in!","head":"dev/test","base":"qa/feat"}'
