name: Branchyng Strategy
on: 
  pull_request:
    types: [ assigned, opened, synchronize ]
    branches:
      - estable/*

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    environment:
      name: estable
    steps:
      - uses: actions/checkout@v3
      - name: Make changes to pull request
        run:
          curl -X POST -u $GITHUB_TOKEN:x-oauth-basic -H "Accept:application/vnd.github+json" https://api.github.com/repos/bgarrido2314/branching-strategy/pulls -d '{"title":"Estable-Preproduccion","body":"Please pull these awesome changes in!","head":"qa/test","base":"estable/test"}'
